sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t pepetata1/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pepetata1/docker-react npm run test
